import { expect, test } from "@playwright/test";

// Deterministic smoke suite — see e2e/README.md for what "deterministic" means
// here and how global-setup.ts gets the local chain into a known state.

test("home page loads", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("HackathonBlockchain4Good")).toBeVisible();
});

test("wallet connect UI is present", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("Connect Wallet")).toBeVisible();
});

test("configured network matches scaffold.config.ts (foundry local chain first)", async ({ page }) => {
  await page.goto("/");
  // RainbowKit's connect flow is the only UI surface for network name pre-
  // connection; we assert indirectly instead by confirming the app fetched
  // the local chain's config without a runtime error (see next test) — the
  // network itself is exercised end-to-end there.
  await expect(page).toHaveTitle(/Scaffold-ETH/i);
});

test("debug page renders the deployed contract and reads its live state", async ({ page }) => {
  await page.goto("/debug");

  // Contract card renders (name from packages/nextjs/contracts/deployedContracts.ts,
  // generated by the local deploy that ran in global-setup.ts).
  await expect(page.getByText("YourContract", { exact: false }).first()).toBeVisible({ timeout: 15_000 });

  // A `view` function's return value is fetched and rendered without any
  // wallet connection — this is the one real end-to-end contract read: it
  // only passes if Anvil is up, the contract is deployed, and the frontend's
  // generated ABI/address actually match what's on-chain.
  await expect(page.getByText("Building Unstoppable Apps!!!", { exact: false })).toBeVisible({ timeout: 15_000 });
});
